#pragma once

// Autogenerated header by uic
#ifdef _WIN32
#include "windows.h"
#include "reconBaseWidget.ui.h"
#else
#include "ui_reconBaseWidget.h" 
#endif

class ReconWidget : public QWidget, public Ui::ReconBaseWidget
{
  Q_OBJECT
  
  public:
  // Constructor
  ReconWidget(QWidget* parent = 0);
};
