# Shared arguments
ARG USERNAME="vscode"
ARG USER_UID=1000
ARG USER_GID=$USER_UID

FROM ubuntu:20.04 AS gadgetron_baseimage

ARG USERNAME
ARG USER_UID
ARG USER_GID
ARG HOME=/home/$USERNAME

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y sudo wget git-core rsync curl net-tools libxml2 libglib2.0-dev default-jdk \
    && apt-get clean

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME -s /bin/bash \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# The version of conda to use
ARG CONDA_VERSION=4.13.0

# Based on https://github.com/ContinuumIO/docker-images/blob/master/miniconda3/debian/Dockerfile.
# We also install conda-lock.
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh \
    && mkdir -p /opt \
    && sh miniconda.sh -b -p /opt/conda \
    && ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh \
    && find /opt/conda/ -follow -type f -name '*.a' -delete \
    && find /opt/conda/ -follow -type f -name '*.js.map' -delete \
    && [ -z "$CONDA_VERSION" ] || /opt/conda/bin/conda install -n base conda=$CONDA_VERSION \
    && /opt/conda/bin/conda install -c conda-forge -n base conda-lock \
    && /opt/conda/bin/conda clean -afy \
    && groupadd -r conda --gid 900 \
    && usermod -aG conda ${USERNAME} \
    && chown -R :conda /opt/conda \
    && chmod -R g+w /opt/conda \
    && find /opt -type d | xargs -n 1 chmod g+s 

# Copy environment, which will be filtered for later staged
COPY --chown=$USER_UID:conda gadgetron/environment.yml /tmp/build/

# Create mount points for tests
RUN mkdir -p /test && chown ${USER_UID}:${USER_GID} /test
VOLUME /test

RUN echo "" >> ${HOME}/.bashrc
RUN echo "MATLABROOT=/usr/local/MATLAB" >> ${HOME}/.bashrc
RUN echo "PATH=/usr/local/MATLAB/bin:/opt/package/bin:$PATH" >> ${HOME}/.bashrc
#RUN echo "MATLABPATH=/opt/code/MATLAB/:/opt/code/MATLAB/:/opt/code/MATLAB/gadgetron-matlab-nhlbi/:/opt/code/MATLAB/gadgetron-matlab-nhlbi/+gadgetron/:/opt/code/MATLAB/gadgetron-matlab-nhlbi/+gadgetron/+nhlbi/:/opt/code/MATLAB/gadgetron-matlab-nhlbi/+gadgetron/+socket/:/opt/code/MATLAB/gadgetron-matlab-nhlbi/java/:/opt/code/MATLAB/gadgetron-matlab-nhlbi/+gadgetron/+examples/:/opt/code/MATLAB/gadgetron-matlab-nhlbi/+gadgetron/+external/:/opt/code/MATLAB/gadgetron-matlab-nhlbi/+gadgetron/+lib/:/opt/code/MATLAB/gadgetron-matlab-nhlbi/+gadgetron/+types/" >> ${HOME}/.bashrc
#RUN echo "MATLABPATH=\"$(find RECURSIVEFOLDER -type d -printf %p:)$MATLABPATH\""
#RUN echo "MATLABPATH=/opt/code/MATLAB" >> ${HOME}/.bashrc
RUN echo "MATLAB_USE_USERWORK=1" >> ${HOME}/.bashrc
# Add a section to /etc/bash.bashrc that ensures that a section is present at the end of ~/.bashrc.
# We can't just write to .bashrc from here because it will be overwritten if the vscode user has
# opted to use their own dotfiles repo. The dotfiles repo is cloned after the postCreateCommand
# in the devcontainer.json file is executed.
RUN echo "\n\
if ! grep -q \"^source /opt/conda/etc/profile.d/conda.sh\" ${HOME}/.bashrc; then\n\
	echo \"source /opt/conda/etc/profile.d/conda.sh\" >> ${HOME}/.bashrc\n\
	echo \"conda activate $(grep 'name:' /tmp/build/environment.yml | awk '{print $2}')\" >> ${HOME}/.bashrc\n\
fi\n" >> /etc/bash.bashrc



ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

FROM gadgetron_baseimage AS gadgetron_dev_cuda
ARG USER_UID
USER ${USER_UID}
RUN grep -v "#.*\<NOFILTER\>" /tmp/build/environment.yml > /tmp/build/filtered_environment.yml
RUN umask 0002 && /opt/conda/bin/conda env create -f /tmp/build/filtered_environment.yml && /opt/conda/bin/conda clean -afy && sudo chown -R :conda /opt/conda
USER root

FROM gadgetron_dev_cuda AS gadgetron_cudabuild
ARG USER_UID
USER ${USER_UID}
WORKDIR /opt
#RUN sudo chown $USER_UID:$USER_GID /opt 
RUN sudo chown ${USER_UID} /opt 
#RUN sudo chgrp ${USER_GID} /opt 
RUN mkdir -p /opt/code/gadgetron && mkdir -p /opt/package
COPY --chown=$USER_UID:conda gadgetron/ /opt/code/gadgetron/
SHELL ["/bin/bash", "-c"]
RUN . /opt/conda/etc/profile.d/conda.sh && umask 0002 && conda activate gadgetron && sh -x && \
    cd /opt/code/gadgetron && \
    mkdir build && \
    cd build && \
    cmake ../ -GNinja -DUSE_MKL=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/package -DUSE_MKL=ON && \
    ninja && \
    ninja install
    
FROM gadgetron_cudabuild AS gadgetron_nhlbicudabuild
ARG USER_UID
USER ${USER_UID}
WORKDIR /opt
#COPY NHLBI TOOLBOX
RUN mkdir -p /opt/code/ITK
COPY --chown=$USER_UID:conda ITK/ /opt/code/ITK/
SHELL ["/bin/bash", "-c"]
RUN . /opt/conda/etc/profile.d/conda.sh && umask 0002 && conda activate gadgetron && sh -x && \
    cd /opt/code/ITK && \
    mkdir build && \
    cd build && \
 ##   cmake ../ -GNinja -DUSE_MKL=ON -DCMAKE_INSTALL_PREFIX=/opt/package && \
     cmake ../ -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/package -DCMAKE_PREFIX_PATH=/opt/package && \
    ninja && \
    ninja install
RUN mkdir -p /opt/code/NHLBI-GT-Non-Cartesian
COPY --chown=$USER_UID:conda NHLBI-GT-Non-Cartesian/ /opt/code/NHLBI-GT-Non-Cartesian/
SHELL ["/bin/bash", "-c"]
RUN . /opt/conda/etc/profile.d/conda.sh && umask 0002 && conda activate gadgetron && sh -x && \
    cd /opt/code/NHLBI-GT-Non-Cartesian && \
    mkdir build && \
    cd build && \
 ##   cmake ../ -GNinja -DUSE_MKL=ON -DCMAKE_INSTALL_PREFIX=/opt/package && \
     cmake ../ -GNinja -DUSE_MKL=ON  -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/package -DCMAKE_PREFIX_PATH=/opt/package && \
    ninja && \
    ninja install
RUN mkdir -p /opt/code/MATLAB/
RUN mkdir -p /home/vscode/Documents/MATLAB/
RUN mkdir -p /home/vscode/.matlab/R2021a/
COPY --chown=$USER_UID:conda gadgetron-matlab-nhlbi/ /home/vscode/Documents/MATLAB/
COPY --chown=$USER_UID:conda gadgetron-matlab-nhlbi/pathdef.m /opt/code/MATLAB/
RUN echo "/home/vscode/Documents/MATLAB/gadgetron.external.SocketWrapper.jar" >> ${HOME}/.matlab/R2021a/javaclasspath.txt
RUN echo "/home/vscode/Documents/MATLAB/java" >> ${HOME}/.matlab/R2021a/javaclasspath.txt
RUN echo "LC_ALL=C" >> ${HOME}/.bashrc
RUN echo "unset LANGUAGE" >> ${HOME}/.bashrc

FROM gadgetron_dev_cuda AS gadgetron_nhlbi_rt_cuda
ARG USER_UID
USER ${USER_UID}
#RUN grep -v "#.*\<dev\>" /tmp/build/environment.yml > /tmp/build/filtered_environment.yml
#RUN umask 0002 && /opt/conda/bin/conda env create -f /tmp/build/filtered_environment.yml && /opt/conda/bin/conda clean -afy && sudo chown -R :conda /opt/conda
COPY --from=gadgetron_nhlbicudabuild --chown=$USER_UID:conda /opt/package /opt/conda/envs/gadgetron/
COPY --from=gadgetron_nhlbicudabuild --chown=$USER_UID:conda /opt/code/gadgetron/docker/entrypoint.sh /opt/
COPY --from=gadgetron_nhlbicudabuild --chown=$USER_UID:conda /opt/code/gadgetron/docker/set_matlab_paths.sh /opt/
RUN chmod +x /opt/entrypoint.sh
RUN sudo mkdir -p /opt/integration-test && sudo chown ${USER_GID}:${USER_UID} /opt/integration-test
COPY --from=gadgetron_cudabuild --chown=$USER_UID:conda /opt/code/gadgetron/test/integration /opt/integration-test/

RUN mkdir -p /home/vscode/Documents/MATLAB/
RUN mkdir -p /home/vscode/.matlab/R2021a/
COPY --chown=$USER_UID:conda gadgetron-matlab-nhlbi/ /home/vscode/Documents/MATLAB/
COPY --chown=$USER_UID:conda gadgetron-matlab-nhlbi/pathdef.m /opt/code/MATLAB/
RUN echo "/home/vscode/Documents/MATLAB/gadgetron.external.SocketWrapper.jar" >> ${HOME}/.matlab/R2021a/javaclasspath.txt
RUN echo "/home/vscode/Documents/MATLAB/java" >> ${HOME}/.matlab/R2021a/javaclasspath.txt
ENTRYPOINT [ "/tini", "--", "/opt/entrypoint.sh" ]
