#ifndef GADGETRON_MRI_NONCARTESIAN_EXPORT_H_
#define GADGETRON_MRI_NONCARTESIAN_EXPORT_H_

#if defined (WIN32)
#if defined (__BUILD_GADGETRON_MRI_NONCARTESIAN__)
#define EXPORTGADGETSMRINONCARTESIAN __declspec(dllexport)
#else
#define EXPORTGADGETSMRINONCARTESIAN __declspec(dllimport)
#endif
#else
#define EXPORTGADGETSMRINONCARTESIAN
#endif

#endif /* GADGETRON_MRI_NONCARTESIAN_EXPORT_H_ */
