#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

me=$(basename "$0")
image=$1

#Get information about the image
created=$(docker inspect --format='{{.Created}}' $image)
timestamp="${created:0:4}${created:5:2}${created:8:2}-${created:11:2}${created:14:2}"
manifest=$(docker run --rm $image cat /opt/manifest.json)

gadgetron_sha1=$(echo $manifest|jq '.io.gadgetron.gadgetron.sha1'| tr -d '"'|cut -c-8)
gtprep_sha1=$(echo $manifest|jq '.io.gadgetron.gtprep.sha1'| tr -d '"' | cut -c-8 )
chroot_name="gadgetron-${timestamp}-${gadgetron_sha1}"
if [ "$gtprep_sha1" != "null"  ]; then
    chroot_name="${chroot_name}-gtprep-${gtprep_sha1}"
fi

chroot_base_name=$chroot_name
chroot_name="${chroot_name}.tar"
echo "Creating chroot image with name: $chroot_name"

docker export $(docker create --name tmpchrootcontainer $image) > ${chroot_name}
docker rm tmpchrootcontainer

if [ $# -gt 1 ]; then
    chroot_img_name=${chroot_base_name}.img
    echo "Creating chroot img file with name: $chroot_img_name"

    chroot_img_size=$2
    chroot_tar_dir=${chroot_base_name}_untar
    mkdir -p ${chroot_tar_dir}
    tar -xf ${chroot_name} --directory=${chroot_tar_dir}

    if [ $# -gt 2 ]; then
        xml_file=$3
        rm -rf ${chroot_tar_dir}/usr/local/share/gadgetron/config/${xml_file}
    fi
    
    chroot_img_dir=${chroot_base_name}
    mkdir -p ${chroot_img_dir}
    dd if=/dev/zero of=${chroot_img_name} bs=1M count=${chroot_img_size}
    mke2fs -F -t ext3 ${chroot_img_name}
    mount -o loop ${chroot_img_name} ${chroot_img_dir}
    cp -rf ${chroot_tar_dir}/* ${chroot_img_dir}
    sleep 3
    umount ${chroot_img_dir}
    rmdir ${chroot_img_dir}
    rm -rf ${chroot_tar_dir}
fi
