#!/bin/bash

#Make sure environment variables are set
export GADGETRON_SUPERVISOR_NODAEMON=${GADGETRON_SUPERVISOR_NODAEMON:-"true"}
export GADGETRON_RELAY_HOST=${GADGETRON_RELAY_HOST:-"127.0.0.1"}
export GADGETRON_LOG_FILENAME=${GADGETRON_LOG_FILENAME:-"/tmp/gadgetron.log"}
export OMP_THREAD_LIMIT=$(($(nproc)*2))
export OMP_WAIT_POLICY=PASSIVE
#export OMP_NUM_THREADS=$(nproc)
export OMP_WAIT_POLICY=passive
#export OMP_DYNAMIC=false
#export OMP_PROC_BIND=true
export OPENBLAS_NUM_THREADS=1
#export HDF5_USE_FILE_LOCKING=FALSE
export LANG=en_US.UTF-8

# if want to ensure high numerical reproducibility, turn on this option
# export MKL_CBWR=COMPATIBLE

supervisord -c "$(dirname "$0")/supervisord.conf" 
