#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

me=$(basename "$0")

if [ "$#" -ne 1 ]; then
    echo "Usage: "
    printf "\t%s <CHROOT FOLDER>\n" "$me"
    exit 1
fi

root_fs=$(realpath $1)

#Remove mounts if they are already there
umount $(mount|grep ${root_fs}|awk '{print $3}') > /dev/null 2>&1

#Bind necessary mounts
mount --bind /proc ${root_fs}/proc 
mount --bind /sys  ${root_fs}/sys
mount --bind /dev  ${root_fs}/dev

#Copy necessary files
cp /etc/hosts ${root_fs}/etc/

#Start the supervisor in the chroot image
chroot ${root_fs} /bin/bash /opt/start_supervisor

