#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

me=$(basename "$0")

if [ "$#" -ne 1 ]; then
    echo "Usage: "
    printf "\t%s <CHROOT FOLDER>\n" "$me"
    exit 1
fi

root_fs=$(realpath $1)

SUPERVISORPID=$(chroot ${root_fs} /usr/bin/supervisorctl pid)

kill -SIGINT ${SUPERVISORPID}
while kill -0 ${SUPERVISORPID} 2> /dev/null; do sleep 1; done;

#Remove mounts if they are already there
umount $(mount|grep ${root_fs}|awk '{print $3}') > /dev/null 2>&1

