#!/bin/bash

me=$(basename "$0")

if [ "$#" -ne 2 ]; then
    echo "Usage:"
    printf "\t%s <IMAGE IN> <IMAGE OUT>\n" "$me"
    exit 1
fi

IMG_IN=$1
IMG_OUT=$2

DOCKERFOLDER=$(mktemp -d)
DOCKER_ENV=$(docker inspect ${IMG_IN}|jq -c .[0].Config.Env[]| tr -d '"'|tr "\n" " ")
echo $DOCKER_ENV

DOCKER_CMD=$(docker inspect ${IMG_IN}|jq -c  .[0].Config.Cmd)
echo $DOCKER_CMD

DOCKER_LABELS=$(docker inspect ${IMG_IN}|jq -c .[0].Config.Labels|tr -d "{}"|tr "," " "|tr ":" "=")
DOCKER_LABELS="${DOCKER_LABELS} \"io.gadgetron.imagetype\"=\"stripped\""
echo $DOCKER_LABELS

cat << EOF > ${DOCKERFOLDER}/Dockerfile
FROM ${IMG_IN}

RUN apt-get remove --yes --autoremove build-essential x11-common libgtk* make cmake
RUN apt-get --yes remove *-dev
#RUN add-apt-repository ppa:lkoppel/ceres
RUN apt-get update
RUN apt-get install --no-install-recommends --no-install-suggests --yes libplplot-dev libdcmtk-dev
RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --no-install-suggests --yes python3-tk
RUN rm -rf /opt/*.tar.gz
RUN rm -rf /usr/local/cuda/bin
RUN rm -rf /usr/local/cuda/doc
RUN rm -rf /usr/local/cuda/extras
RUN rm -rf /usr/local/cuda/include
RUN rm -rf /usr/local/cuda/jre
RUN rm -rf /usr/local/cuda/libnsight
RUN rm -rf /usr/local/cuda/libnvvp
RUN rm -rf /usr/local/cuda/lib64/*.a
RUN rm -rf /usr/local/cuda/nvvm
RUN if [ -f "/opt/intel/lib/intel64/libiomp5.so" ]; then mv /opt/intel/lib/intel64/libiomp5.so /opt/intel/lib/; fi
RUN rm -rf /opt/intel/lib/intel64/*
RUN if [ -f "/opt/intel/lib/libiomp5.so" ]; then mv /opt/intel/lib/libiomp5.so /opt/intel/lib/intel64/; fi
RUN rm -rf /opt/intel/mkl/benchmarks
RUN rm -rf /opt/intel/mkl/bin
RUN rm -rf /opt/intel/mkl/examples
RUN rm -rf /opt/intel/mkl/interfaces
RUN rm -rf /opt/intel/mkl/tests
RUN rm -rf /opt/intel/mkl/tools
RUN rm -rf /opt/intel/mkl/lib/mic
RUN rm -rf /opt/intel/mkl/lib/intel64/locale
RUN rm -rf /opt/intel/mkl/lib/intel64/*.a
RUN rm -rf /opt/intel/mkl/lib/intel64/lib*ilp*.so
EOF

docker build --network=host -t tmpstripimage ${DOCKERFOLDER}
docker export $(docker create --name tmpstripcontainer tmpstripimage) > ${DOCKERFOLDER}/gadgetron_strip_fs.tar
docker rm tmpstripcontainer
docker rmi tmpstripimage
docker import ${DOCKERFOLDER}/gadgetron_strip_fs.tar tmpstripimage

cat << EOF > ${DOCKERFOLDER}/Dockerfile
FROM tmpstripimage

ENV ${DOCKER_ENV}
LABEL ${DOCKER_LABELS}
CMD ${DOCKER_CMD}
EOF
docker build -t ${IMG_OUT} ${DOCKERFOLDER}

docker rmi tmpstripimage
rm -rf ${DOCKERFOLDER}
