{% set major = load_file_regex(load_file='CMakeLists.txt', regex_pattern='(?<=set\(GADGETRON_VERSION_MAJOR )([^\)]+)') %}
{% set minor = load_file_regex(load_file='CMakeLists.txt', regex_pattern='(?<=set\(GADGETRON_VERSION_MINOR )([^\)]+)') %}
{% set patch = load_file_regex(load_file='CMakeLists.txt', regex_pattern='(?<=set\(GADGETRON_VERSION_PATCH )([^\)]+)') %}

package:
  name: gadgetron
  version: {{ major.group(1) }}.{{ minor.group(1) }}.{{ patch.group(1) }}

source:
  path: ../

requirements:
  build:
    - armadillo>=9.900.5
    - boost=1.80.0
    - cmake>=3.21.3
    - cuda-libraries-dev=11.6.1           # [linux64]
    - cuda-libraries=11.6.1               # [linux64]
    - cuda-runtime=11.6.1                 # [linux64]
    - cuda-nvcc=11.6.112                  # [linux64]
    - dcmtk=3.6.1
    - fftw=3.3.9
    - gcc_linux-64=9.4.0                  # [linux64]
    - gadgetron::gadgetron-python>=1.4.1
    - gmock>=1.10.0
    - gxx_linux-64=9.4.0                  # [linux64]
    - gtest=1.10.0
    - h5py=3.2.1
    - hdf5=1.10.6
    - howardhinnant_date=3.0.1
    - ismrmrd::ismrmrd=1.13.1
    - ismrmrd::ismrmrd-python>=1.9.8
    - libblas=*=*mkl
    - libcurl=7.79.1
    - libxml2=2.9
    - mkl>=2022.0.0
    - mkl-include>=2022.0.0
    - ismrmrd::mrd-storage-server=0.0.12
    - ninja=1.10.2
    - nlohmann_json=3.10.4
    - numpy>=1.22.1
    - packaging=21.3
    - pugixml=1.11.4
    - pyfftw>=0.12.0
    - pyyaml>=6.0
    - python=3.9
    - gadgetron::range-v3>=0.11.0
    - sysroot_linux-64=2.17
  run:
    - armadillo>=9.900.5
    - boost=1.80.0
    - cuda-libraries=11.6.1               # [linux64]
    - cuda-runtime=11.6.1                 # [linux64]
    - dcmtk=3.6.1
    - fftw=3.3.9
    - gadgetron::gadgetron-python>=1.4.1
    - h5py=3.2.1
    - hdf5=1.10.6
    - ismrmrd::ismrmrd=1.13.1
    - ismrmrd::ismrmrd-python>=1.9.8
    - jq>=1.6
    - libblas=*=*mkl
    - libcurl=7.79.1
    - libxml2=2.9
    - memkind>=1.10.1
    - mkl>=2022.0.0
    - ismrmrd::mrd-storage-server=0.0.12
    - numpy>=1.22.1
    - onnxruntime=1.10.0
    - pugixml=1.11.4
    - pyfftw>=0.12.0
    - python=3.9
    - scipy=1.7.1
    - sysroot_linux-64=2.17               # [linux64]

test:
  requires:
    - ismrmrd::siemens_to_ismrmrd=1.2.8

about:
  home: https://github.com/gadgetron/gadgetron
  summary: 'Gadgetron Image Reconstruction Framework'
  description: |
    Gadgetron reconstruction server with support libraries and example pipelines.
  dev_url: https://github.com/gadgetron/gadgetron
  doc_url: https://github.com/gadgetron/gadgetron
  doc_source_url: https://github.com/gadgetron/gadgetron/blob/master/README.md
