#ifndef GADGETRON_DISTRIBUTED_GADGETS_EXPORT_H_
#define GADGETRON_DISTRIBUTED_GADGETS_EXPORT_H_

#if defined (WIN32)
#if defined (__BUILD_GADGETRON_DISTRIBUTED_GADGETS__)
#define EXPORTDISTRIBUTEDGADGETS __declspec(dllexport)
#else
#define EXPORTDISTRIBUTEDGADGETS __declspec(dllimport)
#endif
#else
#define EXPORTDISTRIBUTEDGADGETS
#endif

#endif //EXPORTDISTRIBUTEDGADGETS
