#!/bin/bash

# add the user 'gadgetron'
# sudo adduser --system --no-create-home gadgetron
sudo useradd -M gadgetron
sudo usermod -L gadgetron

# start the gadgetron service
sudo start gadgetron_web

