#!/bin/bash

# add the user 'gadgetron'
sudo adduser --system --no-create-home gadgetron

# copy the gadgetron.xml
sudo cp -i ../config/gadgetron.xml.example ../config/gadgetron.xml

# start the gadgetron service
sudo start gadgetron_web
