#!/bin/bash

# add the user 'gadgetron'
sudo adduser --system --no-create-home gadgetron

# copy the gadgetron.xml
sudo cp -i ../config/gadgetron.xml.example ../config/gadgetron.xml

# create the symbolic link for gadgetron
sudo ln -s /usr/local/gadgetron/bin/gadgetron /usr/local/bin/gadgetron
sudo ln -s /usr/local/gadgetron/bin/ismrmrd_client /usr/local/bin/ismrmrd_client
sudo ln -s /usr/local/gadgetron/bin/gt_alive /usr/local/bin/gt_alive

# start the gadgetron service
sudo start gadgetron_web

