#!/bin/bash

# remove the gadgetron.xml
sudo rm -f /usr/local/gadgetron/config/gadgetron.xml

# remove the symbolic link for gadgetron
sudo rm -f /usr/local/bin/gadgetron
sudo rm -f /usr/local/bin/gadgetron_ismrmrd_client
sudo rm -f /usr/local/bin/gt_alive

# update library path
sudo ldconfig

