#!/usr/bin/perl


use FindBin;
use lib $FindBin::Bin;

my $file = $ARGV[0];

my $new_root = $ARGV[1];

my $gadgetron_root = $ARGV[2];

my $deps = `$FindBin::Bin/get_dependencies_for_binary $file`;

my @lines = split('\n', $deps);

system("sudo cp -n $file $new_root/$gadgetron_root/lib/");

foreach my $val (@lines) {
    chomp($val);
    if (not -e "$new_root/$val")
    {
        system("$FindBin::Bin/copy_file_and_dependencies $val $new_root $gadgetron_root");
    }
}
