#!/usr/bin/perl                                                                                                                                              
use FindBin;
use lib $FindBin::Bin;

my $gadgetron_root = $ARGV[0];
my $new_root = $ARGV[1];

my $directory = $gadgetron_root . "/bin";

opendir (DIR, $new_root . $directory) or die $!;
while (my $file = readdir(DIR)) {
    next if ($file =~ m/^\./);
    my $deps = `$FindBin::Bin/get_dependencies_for_binary $new_root/$directory/$file`;
    my @lines = split('\n', $deps);

    foreach my $val (@lines) {
	chomp($val);
        if (not -e "$new_root/$val")
        {
            system("$FindBin::Bin/copy_file_and_dependencies $val $new_root $gadgetron_root");
        }
    }
}
closedir(DIR);


$directory = $gadgetron_root . "/lib";

opendir (DIR, $new_root . $directory) or die $!;
while (my $file = readdir(DIR)) {
    next unless ($file =~ m/\.so$/);

    my $deps = `$FindBin::Bin/get_dependencies_for_binary $new_root/$directory/$file`;
    my @lines = split('\n', $deps);

    foreach my $val (@lines) 
    {
	chomp($val);
        if (not -e "$new_root/$val")
        {
            system("$FindBin::Bin/copy_file_and_dependencies $val $new_root $gadgetron_root");
        }
    }
}
closedir(DIR);
