#!/usr/bin/perl

use strict;
use warnings;
use FindBin;
use lib $FindBin::Bin;

my $directory = $ARGV[0] . "/bin";

opendir (DIR, $directory) or die $!;
while (my $file = readdir(DIR)) {
    next if ($file =~ m/^\./);
    system("$FindBin::Bin/get_dependencies_for_binary $ARGV[0]/bin/$file\n");
}
closedir(DIR);


$directory = $ARGV[0] . "/lib";

opendir (DIR, $directory) or die $!;
while (my $file = readdir(DIR)) {
    next unless ($file =~ m/\.so$/);
    system("$FindBin::Bin/get_dependencies_for_binary $ARGV[0]/lib/$file\n");
}
closedir(DIR);
