#ifndef GADGETRON_INTERVENTIONAL_MRI_EXPORT_H_
#define GADGETRON_INTERVENTIONAL_MRI_EXPORT_H_

#if defined (WIN32)
#if defined (__BUILD_GADGETRON_INTERVENTIONAL_MRI__)
#define EXPORTGADGETSINTERVENTIONAL_MRI __declspec(dllexport)
#else
#define EXPORTGADGETSINTERVENTIONAL_MRI __declspec(dllimport)
#endif
#else
#define EXPORTGADGETSINTERVENTIONAL_MRI
#endif

#endif /* GADGETRON_INTERVENTIONAL_MRI_EXPORT_H_ */
