#ifndef GADGETMRIHEADERS_H
#define GADGETMRIHEADERS_H

#include <ace/Basic_Types.h>

//Data flags
/*
#define GADGET_FLAG_ACQ_END                   (1 << 0)
#define GADGET_FLAG_LAST_ACQ_IN_SLICE         (1 << 1)
#define GADGET_FLAG_LAST_ACQ_IN_MEAS          (1 << 2)
#define GADGET_FLAG_LAST_ACQ_IN_CONCAT        (1 << 3)
#define GADGET_FLAG_FIRST_ACQ_IN_SLICE        (1 << 4)
#define GADGET_FLAG_FIRST_ACQ_IN_MEAS         (1 << 5)
#define GADGET_FLAG_FIRST_ACQ_IN_CONCAT       (1 << 6)
#define GADGET_FLAG_IS_NOISE_SCAN             (1 << 7)
#define GADGET_FLAG_IS_PATREF_SCAN            (1 << 8)
#define GADGET_FLAG_IS_PATREFANDIMA_SCAN      (1 << 9)

#define GADGET_FLAG_LAST_IMAGE                (1 << 0)

enum GadgetImageFormats {
	GADGET_IMAGE_COMPLEX_FLOAT = 0,
	GADGET_IMAGE_REAL_FLOAT,
	GADGET_IMAGE_REAL_UNSIGNED_SHORT
};

enum GadgetImageTypes
{
	GADGET_IMAGE_MAGNITUDE = 0,
	GADGET_IMAGE_PHASE,
	GADGET_IMAGE_REAL,
	GADGET_IMAGE_IMAG
};
*/

enum GadgetMessageID {
  GADGET_MESSAGE_EXT_ID_MIN                = 1000,
  GADGET_MESSAGE_ACQUISITION               = 1001, /**< DEPRECATED */
  GADGET_MESSAGE_NEW_MEASUREMENT           = 1002, /**< DEPRECATED */
  GADGET_MESSAGE_END_OF_SCAN               = 1003, /**< DEPRECATED */
  GADGET_MESSAGE_IMAGE_CPLX_FLOAT          = 1004, /**< DEPRECATED */
  GADGET_MESSAGE_IMAGE_REAL_FLOAT          = 1005, /**< DEPRECATED */
  GADGET_MESSAGE_IMAGE_REAL_USHORT         = 1006, /**< DEPRECATED */
  GADGET_MESSAGE_EMPTY                     = 1007, /**< DEPRECATED */
  GADGET_MESSAGE_ISMRMRD_ACQUISITION       = 1008,
  GADGET_MESSAGE_ISMRMRD_IMAGE_CPLX_FLOAT  = 1009,
  GADGET_MESSAGE_ISMRMRD_IMAGE_REAL_FLOAT  = 1010,
  GADGET_MESSAGE_ISMRMRD_IMAGE_REAL_USHORT = 1011,
  GADGET_MESSAGE_DICOM                     = 1012,
  GADGET_MESSAGE_EXT_ID_MAX                = 4096
};


#endif  //GADGETMRIHEADERS_H
