#pragma once

// Autogenerated header by uic
#include "ui_reconBaseWidget.h" 

class ReconWidget : public QWidget, public Ui::ReconBaseWidget
{
  Q_OBJECT
  
  public:
  // Constructor
  ReconWidget(QWidget* parent = 0);
};
