
#install dependencies
if (HDF5_FOUND)
    if(DEFINED ENV{HDF5_ROOT})
        set(HDF5_BIN_DIR $ENV{HDF5_ROOT}/bin)
    else ()
        set(HDF5_BIN_DIR ${HDF5_C_INCLUDE_DIR}/../bin)
    endif ()
    message("Install hdf5 libraries from ${HDF5_BIN_DIR} ")

    file(GLOB HDF5_DLL ${HDF5_BIN_DIR}/*.dll)
    foreach(fileName ${HDF5_DLL})
        message("Install ${fileName} ")
        install( FILES ${fileName} DESTINATION lib COMPONENT main)
    endforeach()
endif ()

if (MKL_FOUND)
    if (HAS_64_BIT)
        set(MKL_REDIST_DIR ${MKLROOT_PATH}/redist/intel64)
    else ()
        set(MKL_REDIST_DIR ${MKLROOT_PATH}/redist/ia32)
    endif ()

    message("Install mkl libraries from ${MKL_REDIST_DIR}/compiler ")
    file(GLOB MKL_DLL ${MKL_REDIST_DIR}/compiler/*iomp5md*.dll)
    foreach(fileName ${MKL_DLL})
        message("Install ${fileName} ")
        install( FILES ${fileName} DESTINATION lib COMPONENT main)
    endforeach()
endif ()

if (ACE_FOUND)
    message("Install ACE libraries from ${ACE_INCLUDE_DIR}/lib ")
    file(GLOB ACE_DLL ${ACE_INCLUDE_DIR}/lib/ACE.dll)
    foreach(fileName ${ACE_DLL})
        message("Install ${ACE_DLL} ")
        install( FILES ${ACE_DLL} DESTINATION lib COMPONENT main)
    endforeach()
endif ()

if (ARMADILLO_FOUND)
    message("Install ARMADILLO libraries from ${ARMADILLO_INCLUDE_DIRS}/../lib ")
    file(GLOB ARMADILLO_DLL ${ARMADILLO_INCLUDE_DIRS}/../lib/*.dll)
    foreach(fileName ${ARMADILLO_DLL})
        message("Install ${fileName} ")
        install( FILES ${fileName} DESTINATION lib COMPONENT main)
    endforeach()
endif ()

if (FFTW3_FOUND)
    message("Install FFTW3 libraries from ${FFTW3_INCLUDE_DIR} ")
    file(GLOB FFTW3_DLL ${FFTW3_INCLUDE_DIR}/*.dll)
    foreach(fileName ${FFTW3_DLL})
        message("Install ${fileName} ")
        install( FILES ${fileName} DESTINATION lib COMPONENT main)
    endforeach()
endif ()

if (ISMRMRD_FOUND)
    message("Install ISMRMRD libraries from ${ISMRMRD_LIBRARY_DIRS} ")
    file(GLOB ISMRMRD_DLL ISMRMRD_LIBRARY_DIRS/ismrmrd.dll)
    foreach(fileName ${ISMRMRD_DLL})
        message("Install ${fileName} ")
        install( FILES ${fileName} DESTINATION lib COMPONENT main)
    endforeach()
endif ()

if (Boost_FOUND)
    message("Install BOOST libraries from ${Boost_LIBRARY_DIR_RELEASE} ")
    file(GLOB BOOST_CHRONO_DLL ${Boost_LIBRARY_DIR_RELEASE}/boost_chrono*.dll)
    foreach(fileName ${BOOST_CHRONO_DLL})
        message("Install ${fileName} ")
        install( FILES ${fileName} DESTINATION lib COMPONENT main)
    endforeach()

    file(GLOB BOOST_DATE_TIME_DLL ${Boost_LIBRARY_DIR_RELEASE}/boost_date_time*.dll)
    foreach(fileName ${BOOST_DATE_TIME_DLL})
        message("Install ${fileName} ")
        install( FILES ${fileName} DESTINATION lib COMPONENT main)
    endforeach()

    file(GLOB BOOST_PROGRAM_OPTIONS_DLL ${Boost_LIBRARY_DIR_RELEASE}/boost_program_options*.dll)
    foreach(fileName ${BOOST_PROGRAM_OPTIONS_DLL})
        message("Install ${fileName} ")
        install( FILES ${fileName} DESTINATION lib COMPONENT main)
    endforeach()

    if (Boost_PYTHON_FOUND AND PYTHONLIBS_FOUND AND NUMPY_FOUND)
        file(GLOB BOOST_PYTHON_DLL ${Boost_LIBRARY_DIR_RELEASE}/boost_python*.dll)
        foreach(fileName ${BOOST_PYTHON_DLL})
            message("Install ${fileName} ")
            install( FILES ${fileName} DESTINATION lib COMPONENT main)
        endforeach()
    endif ()

    file(GLOB BOOST_SYSTEM_DLL ${Boost_LIBRARY_DIR_RELEASE}/boost_system*.dll)
    foreach(fileName ${BOOST_SYSTEM_DLL})
        message("Install ${fileName} ")
        install( FILES ${fileName} DESTINATION lib COMPONENT main)
    endforeach()

    file(GLOB BOOST_THREAD_DLL ${Boost_LIBRARY_DIR_RELEASE}/boost_thread*.dll)
    foreach(fileName ${BOOST_THREAD_DLL})
        message("Install ${fileName} ")
        install( FILES ${fileName} DESTINATION lib COMPONENT main)
    endforeach()

    file(GLOB BOOST_FILESYSTEM_DLL ${Boost_LIBRARY_DIR_RELEASE}/boost_filesystem*.dll)
    foreach(fileName ${BOOST_FILESYSTEM_DLL})
        message("Install ${fileName} ")
        install( FILES ${fileName} DESTINATION lib COMPONENT main)
    endforeach()
endif ()

if (DCMTK_FOUND)
    message("Install DCMTK libraries from ${DCMTK_DIR}/lib ")
    file(GLOB DCMTK_DLL ${DCMTK_DIR}/lib/*.dll)
    foreach(fileName ${DCMTK_DLL})
        message("Install ${fileName} ")
        install( FILES ${fileName} DESTINATION lib COMPONENT main)
    endforeach()
endif ()

if (GTEST_FOUND)
    message("Install GTEST libraries from ${DCMTK_DIR}/lib ")

    get_filename_component(GTEST_LIB_NAME ${GTEST_LIBRARY} NAME_WE)
    get_filename_component(GTEST_DLL ${GTEST_LIBRARY} DIRECTORY)
    message("Install ${GTEST_DLL}/${GTEST_LIB_NAME}.dll ")
    install( FILES ${GTEST_DLL}/${GTEST_LIB_NAME}.dll DESTINATION lib COMPONENT main)

    get_filename_component(GTEST_MAIN_NAME ${GTEST_MAIN_LIBRARY} NAME_WE)
    get_filename_component(GTEST_MAIN_DLL ${GTEST_MAIN_LIBRARY} DIRECTORY)
    message("Install ${GTEST_MAIN_DLL}/${GTEST_MAIN_NAME}.dll ")
    install( FILES ${GTEST_MAIN_DLL}/${GTEST_MAIN_NAME}.dll DESTINATION lib COMPONENT main)
endif ()
