#ifndef GADGETRON_DISTRIBUTED_GADGETS_EXPORT_H_
#define GADGETRON_DISTRIBUTED_GADGETS_EXPORT_H_

#if defined (WIN32)
#if defined (__BUILD_GADGETRON_COMPRESSION_GADGETS__)
#define EXPORTCOMPRESSEDGADGETS __declspec(dllexport)
#else
#define EXPORTCOMPRESSEDGADGETS __declspec(dllimport)
#endif
#else
#define EXPORTCOMPRESSEDGADGETS
#endif

#endif //EXPORTCOMPRESSEDGADGETS
